name: padracing
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  collection: ^1.18.0
  flame: ^1.19.0
  flame_forge2d: ^0.18.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0

dev_dependencies:
  flame_lint: ^1.2.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true